export const TOGGLE__THEME = 'TOGGLE__THEME'
export const REQUEST__SUCCESS = 'REQUEST__SUCCESS'
export const REQUEST__ERROR = 'REQUEST__ERROR'
export const SEARCH__USER = 'SEARCH__USER'
export const LOGIN = 'LOGIN'
export const REQUESTING = 'REQUESTING'
